name: build-cli

on:
  workflow_dispatch:

jobs:
  build-cli:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            vcpkg_triplet: x64-linux
            target: x86_64-unknown-linux-gnu
          - os: macos-13
            vcpkg_triplet: x64-osx
            target: x86_64-apple-darwin
          - os: macos-13
            vcpkg_triplet: arm64-osx
            target: aarch64-apple-darwin
          - os: windows-2022
            vcpkg_triplet: x64-windows-static-md
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: gerlero/brew-install@v1
        if: runner.os == 'macOS'
        with:
          packages: nasm

      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: runner.os == 'Linux'
        with:
          packages: nasm
          version: 1.0

      - name: vcpkg build
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          pkgs: ffmpeg
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}-${{ matrix.config.vcpkg_triplet }}-${{ hashFiles('vcpkg.json') }}
          token: ${{ github.token }}

      - name: Set VCPKG_ROOT environment variable
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $GITHUB_ENV
          echo "${{ github.workspace }}/vcpkg" >> $GITHUB_PATH

      - name: Set VCPKG_ROOT environment variable
        if: runner.os == 'Windows'
        run: |
          echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $ENV:GITHUB_ENV
          echo "${{ github.workspace }}/vcpkg" >> $ENV:GITHUB_PATH

      - uses: dtolnay/rust-toolchain@stable

      - name: Add target architecture
        run: rustup target add ${{ matrix.config.target }}

      - name: cli build
        run: |
          cargo build --release --features=cli,ffmpeg7_1,link_vcpkg_ffmpeg --target ${{ matrix.config.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bbdd-${{ matrix.config.target }}
          path: target/${{ matrix.config.target }}/release/bbdd*
          if-no-files-found: error
